#!/usr/bin/env python3
"""
task5_cartesian_motion.py — UR5 linear Cartesian motion live in Isaac Sim 6.0
=============================================================================

Drives the UR5 in Isaac Sim along the linear Cartesian path generated by
``task2_trajectory_planner`` (quintic-blended position, damped-pseudo-
inverse IK, no Isaac Sim dependency in that file). A live matplotlib
dashboard updates in lockstep with the playback so a screenshot captures
both the rendered scene and the planning plots together.

What it does:

  1. Builds the Isaac Sim scene (wooden desk + lights + UR5) using the
     shared helpers in ``ur5_scene.py``.
  2. Pre-computes the joint trajectory offline (200 samples in <1 s).
  3. Opens a Qt5Agg matplotlib window with the same five panels as
     task2's dashboard — but with mutable "now" cursors and a current-
     pose stick figure that we redraw each frame.
  4. Streams ``articulation.set_dof_positions(joints[i])`` to the
     simulator at 60 Hz, updating the dashboard every 5 frames (12 Hz).
  5. Holds the final pose, then waits until the user closes the
     simulator window.

Run:

    /home/ubuntu/Simulators/isaacsim-6.0/python.sh \\
        /home/ubuntu/ur5-kinematics-project/task5_cartesian_motion.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# CLI — parsed before SimulationApp so kit doesn't swallow our flags
# ---------------------------------------------------------------------------
_parser = argparse.ArgumentParser(
    description="UR5 linear Cartesian motion in Isaac Sim 6.0",
    add_help=False,
)
_parser.add_argument("--motion-time", type=float, default=5.0,
                     help="Trajectory duration in seconds (default 5.0)")
_parser.add_argument("--dwell-end",   type=float, default=2.0,
                     help="Seconds to hold the final pose (default 2.0)")
_parser.add_argument("--dashboard", choices=("live", "static", "off"),
                     default="live",
                     help="Dashboard mode: live (default), static, or off")
_parser.add_argument("--samples", type=int, default=200,
                     help="Trajectory samples (default 200)")
cli, _unknown = _parser.parse_known_args()

# ---------------------------------------------------------------------------
# SimulationApp — must come before any Isaac Sim or matplotlib Qt import
# ---------------------------------------------------------------------------
from isaacsim import SimulationApp

simulation_app = SimulationApp({
    "headless": False,
    "width":  1920,
    "height": 1080,
})

# ---------------------------------------------------------------------------
# All remaining imports — after SimulationApp()
# ---------------------------------------------------------------------------
import math
import time

import numpy as np
import omni.timeline
import omni.usd
from pxr import Gf, UsdGeom

import isaacsim.core.experimental.utils.stage as stage_utils
from isaacsim.core.experimental.objects import GroundPlane
from isaacsim.core.experimental.prims import Articulation

# Shared scene helpers (lights, desk, UR5 paths, step pacer)
sys.path.insert(0, str(Path(__file__).parent))
from ur5_scene import (
    ROBOT_BASE_Z,
    ROBOT_NAME,
    ROBOT_PRIM_PATH,
    build_desk,
    build_lights,
    make_step_pacer,
    resolve_ur5_usd,
)

# Analytical planner from task 2 (no Isaac Sim dependency)
from task2_trajectory_planner import (
    fk_chain,
    fk_position,
    generate_trajectory,
    solve_joint_trajectory,
)

# Matplotlib — set Qt5Agg before pyplot so the window opens next to Isaac Sim
import matplotlib
matplotlib.use("Qt5Agg")
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (registers 3-D projection)

# ---------------------------------------------------------------------------
# Trajectory endpoints (kept hard-coded per the plan)
# ---------------------------------------------------------------------------
P_START = np.array([0.40, -0.30, 0.50])
P_END   = np.array([0.40,  0.30, 0.50])

# Starting joint vector for warm-starting IK at the first sample.
Q_INIT = np.array([
    0.0, -math.pi / 2, math.pi / 2, -math.pi / 2, -math.pi / 2, 0.0,
])

NUM_DOF = 6
DASHBOARD_EVERY = 5     # update plots every Nth sim frame (60 Hz / 5 = 12 Hz)


# ---------------------------------------------------------------------------
# Live dashboard — 5 panels, with mutable artists for the time cursor and
# the current-pose stick figure.
# ---------------------------------------------------------------------------
def _build_live_dashboard(
    t:          np.ndarray,
    positions:  np.ndarray,
    velocities: np.ndarray,
    speed:      np.ndarray,
    joints:     np.ndarray,
) -> tuple[plt.Figure, dict]:
    plt.rcParams.update({
        "font.family":     "DejaVu Sans",
        "axes.titlesize":  11,
        "axes.labelsize":  10,
        "legend.fontsize": 9,
        "figure.facecolor": "white",
    })
    fig = plt.figure(figsize=(15, 9))
    gs = GridSpec(
        3, 2, figure=fig,
        height_ratios=[3.0, 3.0, 1.1],
        hspace=0.35, wspace=0.22,
        left=0.06, right=0.97, top=0.93, bottom=0.05,
    )

    # ---- Panel 1: live 3-D stick figure --------------------------------
    ax1 = fig.add_subplot(gs[0, 0], projection="3d")
    ax1.set_title("Stick Figure — live")
    ax1.plot(positions[:, 0], positions[:, 1], positions[:, 2],
             linestyle=":", color="dimgray", alpha=0.7)
    ax1.scatter(*P_START, c="#1f77b4", s=60, marker="X", label="Start")
    ax1.scatter(*P_END,   c="#2ca02c", s=60, marker="X", label="End")
    chain0 = np.array([T[:3, 3] for T in fk_chain(joints[0])])
    live_arm, = ax1.plot(
        chain0[:, 0], chain0[:, 1], chain0[:, 2],
        color="#d62728", marker="o", markersize=5, linewidth=2.5, label="Now",
    )
    ax1.set_xlabel("X (m)"); ax1.set_ylabel("Y (m)"); ax1.set_zlabel("Z (m)")
    ax1.legend(loc="upper left", fontsize=8)
    # Equal-axes for the 3-D box (fixed extents from the static trajectory).
    pts = np.vstack([positions, np.array([P_START, P_END])])
    mins, maxs = pts.min(axis=0) - 0.4, pts.max(axis=0) + 0.4
    span = (maxs - mins).max()
    mids = 0.5 * (maxs + mins)
    ax1.set_xlim(mids[0] - span / 2, mids[0] + span / 2)
    ax1.set_ylim(mids[1] - span / 2, mids[1] + span / 2)
    ax1.set_zlim(mids[2] - span / 2, mids[2] + span / 2)

    # ---- Panel 2: EE position vs time + cursor --------------------------
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.set_title("EE Cartesian Position vs Time")
    ax2.plot(t, positions[:, 0], label="X", color="#d62728", linewidth=2)
    ax2.plot(t, positions[:, 1], label="Y", color="#2ca02c", linewidth=2)
    ax2.plot(t, positions[:, 2], label="Z", color="#1f77b4", linewidth=2)
    cur_pos = ax2.axvline(t[0], color="black", linewidth=1.2, alpha=0.7)
    ax2.set_xlabel("time (s)"); ax2.set_ylabel("position (m)")
    ax2.grid(True, alpha=0.3); ax2.legend(loc="best")

    # ---- Panel 3: EE speed vs time + cursor -----------------------------
    ax3 = fig.add_subplot(gs[1, 0])
    ax3.set_title("EE Linear-Velocity Magnitude  (quintic bell curve)")
    ax3.plot(t, speed, color="#9467bd", linewidth=2.4)
    ax3.fill_between(t, 0.0, speed, color="#9467bd", alpha=0.18)
    peak = float(speed.max())
    ax3.axhline(peak, ls="--", color="#9467bd", alpha=0.6,
                label=f"peak |v| = {peak:.3f} m/s")
    cur_vel = ax3.axvline(t[0], color="black", linewidth=1.2, alpha=0.7)
    ax3.set_xlabel("time (s)"); ax3.set_ylabel("|v| (m/s)")
    ax3.grid(True, alpha=0.3); ax3.legend(loc="upper right")

    # ---- Panel 4: joint angles vs time + cursor -------------------------
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.set_title("Joint Angles vs Time")
    palette = plt.cm.tab10(np.linspace(0.0, 1.0, NUM_DOF))
    for j in range(NUM_DOF):
        ax4.plot(t, np.degrees(joints[:, j]),
                 label=fr"$\theta_{{{j + 1}}}$",
                 color=palette[j], linewidth=1.8)
    cur_joints = ax4.axvline(t[0], color="black", linewidth=1.2, alpha=0.7)
    ax4.set_xlabel("time (s)"); ax4.set_ylabel(r"angle (deg)")
    ax4.grid(True, alpha=0.3); ax4.legend(loc="upper right", ncol=3)

    # ---- Panel 5: equations + parameters --------------------------------
    ax5 = fig.add_subplot(gs[2, :])
    ax5.axis("off")
    distance = float(np.linalg.norm(P_END - P_START))
    params = (
        rf"$\mathbf{{P_0}}=({P_START[0]:.2f},\,{P_START[1]:.2f},\,{P_START[2]:.2f})$\,m"
        rf"$\quad\mathbf{{P_f}}=({P_END[0]:.2f},\,{P_END[1]:.2f},\,{P_END[2]:.2f})$\,m"
        rf"$\quad T={cli.motion_time:.1f}$\,s"
        rf"$\quad\|\Delta\mathbf{{P}}\|={distance:.3f}$\,m"
        rf"$\quad v_{{\max}}=\frac{{15}}{{8}}\,\|\Delta\mathbf{{P}}\|/T={1.875*distance/cli.motion_time:.3f}$\,m/s"
    )
    eqns = "\n".join([
        r"$\mathbf{Cartesian\ Path}:\quad "
        r"\mathbf{P}(t) = \mathbf{P_0} + (\mathbf{P_f} - \mathbf{P_0})\,s(t)"
        r"\qquad\dot{\mathbf{P}}(t) = (\mathbf{P_f} - \mathbf{P_0})\,\dot{s}(t)$",
        r"$\mathbf{Quintic\ Blend}:\quad "
        r"s(\tau)=10\tau^3-15\tau^4+6\tau^5\qquad"
        r"\dot{s}(\tau)=\frac{1}{T}\,(30\tau^2-60\tau^3+30\tau^4)\qquad\tau=t/T$",
        r"$\mathbf{Damped\ IK\ Update}:\quad "
        r"\mathbf{q}_{k+1} = \mathbf{q}_k + \alpha\,J^{T}\,"
        r"(J\,J^{T} + \lambda^{2}\,I)^{-1}\,"
        r"[\mathbf{p}_{\mathrm{target}} - \mathrm{FK}(\mathbf{q}_k)]$",
        params,
    ])
    ax5.text(0.5, 0.5, eqns, ha="center", va="center",
             fontsize=12.5, linespacing=1.7)

    fig.suptitle(
        "UR5 Task 5 — Live Cartesian Motion + Trajectory Dashboard",
        fontsize=15, fontweight="bold",
    )
    return fig, {
        "live_arm":   live_arm,
        "cur_pos":    cur_pos,
        "cur_vel":    cur_vel,
        "cur_joints": cur_joints,
    }


def _update_live_dashboard(
    artists: dict, joints_i: np.ndarray, t_now: float,
) -> None:
    chain = np.array([T[:3, 3] for T in fk_chain(joints_i)])
    artists["live_arm"].set_data_3d(chain[:, 0], chain[:, 1], chain[:, 2])
    for key in ("cur_pos", "cur_vel", "cur_joints"):
        artists[key].set_xdata([t_now, t_now])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    # ---- offline planning (no Isaac Sim work in this block) ------------
    print(f"\n[task5] planning quintic Cartesian path: "
          f"{tuple(P_START)} -> {tuple(P_END)} over {cli.motion_time:.1f} s")
    t, positions, velocities, speed = generate_trajectory(
        P_START, P_END, cli.motion_time, cli.samples,
    )
    joints = solve_joint_trajectory(positions, Q_INIT)
    residual = np.array([
        float(np.linalg.norm(fk_position(joints[i]) - positions[i]))
        for i in range(cli.samples)
    ])
    print(f"[task5] IK max residual : {residual.max() * 1000:.3f} mm")
    print(f"[task5] peak EE speed   : {speed.max():.3f} m/s")

    # ---- Isaac Sim scene -----------------------------------------------
    stage = omni.usd.get_context().get_stage()
    GroundPlane(paths="/World/Ground")
    build_lights()
    build_desk(stage)

    usd_path = resolve_ur5_usd()
    print(f"[task5] UR5 asset       : {usd_path}")
    stage_utils.add_reference_to_stage(usd_path=usd_path, path=ROBOT_PRIM_PATH)

    robot_prim = stage.GetPrimAtPath(ROBOT_PRIM_PATH)
    xf = UsdGeom.Xformable(robot_prim)
    xf.ClearXformOpOrder()
    xf.AddTranslateOp().Set(Gf.Vec3d(0.0, 0.0, ROBOT_BASE_Z))

    omni.timeline.get_timeline_interface().play()
    for _ in range(3):
        simulation_app.update()

    articulation = Articulation(paths=ROBOT_PRIM_PATH)
    print(f"[task5] UR5 articulation: {articulation.num_joints} joints")

    step = make_step_pacer(simulation_app)

    # ---- dashboard ------------------------------------------------------
    fig, artists = None, None
    if cli.dashboard != "off":
        fig, artists = _build_live_dashboard(
            t, positions, velocities, speed, joints,
        )
        if cli.dashboard == "live":
            plt.show(block=False)
            fig.canvas.draw_idle()
            fig.canvas.flush_events()

    # ---- main loop: stream joint commands + pump dashboard -------------
    print(f"[task5] streaming {len(t)} joint commands @ 60 Hz "
          f"(dashboard refresh every {DASHBOARD_EVERY} frames)")
    for i in range(len(t)):
        articulation.set_dof_positions(
            joints[i].reshape(1, -1).astype(np.float32),
        )
        if (cli.dashboard == "live"
                and artists is not None
                and i % DASHBOARD_EVERY == 0):
            _update_live_dashboard(artists, joints[i], float(t[i]))
            fig.canvas.draw_idle()
            fig.canvas.flush_events()
        step()

    # Final frame for the dashboard, then hold the pose.
    if cli.dashboard == "live" and artists is not None:
        _update_live_dashboard(artists, joints[-1], float(t[-1]))
        fig.canvas.draw_idle()
        fig.canvas.flush_events()

    for _ in range(max(0, int(cli.dwell_end * 60))):
        step()

    if cli.dashboard == "static" and fig is not None:
        _update_live_dashboard(artists, joints[-1], float(t[-1]))
        plt.show(block=False)
        fig.canvas.draw_idle()
        fig.canvas.flush_events()

    print("[task5] done — close the Isaac Sim window to exit.")
    while simulation_app.is_running():
        if fig is not None:
            fig.canvas.flush_events()
        step()
    simulation_app.close()


if __name__ == "__main__":
    main()
